// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var ALLOWED_EMAIL = "joaooz123@gmail.com";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Returns the identity of the signed-in Rhema Care Flow user calling the MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (email?.toLowerCase() !== ALLOWED_EMAIL) {
      return {
        content: [{ type: "text", text: `Access denied for ${email ?? "unknown user"}.` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ userId: ctx.getUserId(), email }, null, 2)
        }
      ]
    };
  }
});

// src/lib/mcp/tools/list-patients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var ALLOWED_EMAIL2 = "joaooz123@gmail.com";
function ensureAllowed(ctx) {
  if (!ctx.isAuthenticated()) return "Not authenticated";
  const email = ctx.getUserEmail()?.toLowerCase();
  if (email !== ALLOWED_EMAIL2) return `Access denied for ${email ?? "unknown user"}.`;
  return null;
}
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patients_default = defineTool2({
  name: "list_patients",
  title: "List patients",
  description: "List the signed-in clinician's patient cards from the Rhema Care Flow database (respects Row Level Security).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of patient cards to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const denied = ensureAllowed(ctx);
    if (denied) return { content: [{ type: "text", text: denied }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("patient_cards").select("id, patient_code, diagnosis_tags, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Query failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, rows: data }, null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rqaqdhmdeyzyjglhxrne";
var mcp_default = defineMcp({
  name: "rhema-care-flow-mcp",
  title: "Rhema Care Flow MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Rhema Care Flow clinical workspace. Access is restricted to the workspace owner (joaooz123@gmail.com); every tool re-checks the signed-in user and calls the database with the caller's JWT so Row Level Security applies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_patients_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
