// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const CANONICAL_SUPABASE_PROJECT_ID = "rfsaxstpfpigrjyiochi";
const CANONICAL_SUPABASE_URL = "https://rfsaxstpfpigrjyiochi.supabase.co";
const CANONICAL_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_J8dthJB66ld8lhRIg4e8SA_ro6sr_na";

const DEPRECATED_SUPABASE_PROJECT_IDS = new Set(["rqaqdhmdeyzyjglhxrne"]);

function clean(value: string | undefined): string | undefined {
  if (!value) return undefined;

  return value
    .trim()
    .replace(/[\u200B-\u200D\uFEFF]/g, "")
    .replace(/^["'`“”‘’]+|["'`“”‘’]+$/g, "")
    .replace(/\s+/g, "");
}

function extractProjectIdFromUrl(value: string | undefined): string | undefined {
  const match = value?.match(/^https:\/\/([a-z0-9-]+)\.supabase\.co$/i);
  return match?.[1];
}

function isCanonicalUrl(value: string | undefined): value is string {
  return extractProjectIdFromUrl(value) === CANONICAL_SUPABASE_PROJECT_ID;
}

function isDeprecatedUrl(value: string | undefined): boolean {
  const projectId = extractProjectIdFromUrl(value);
  return Boolean(projectId && DEPRECATED_SUPABASE_PROJECT_IDS.has(projectId));
}

const envUrl = clean(import.meta.env.VITE_SUPABASE_URL as string | undefined);
const envProjectId = clean(import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined);
const envKey = clean(
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY) as string | undefined,
);

if (isDeprecatedUrl(envUrl) || DEPRECATED_SUPABASE_PROJECT_IDS.has(envProjectId ?? "")) {
  console.warn(
    `[Supabase] Deprecated project detected: ${envProjectId || envUrl}. Using canonical project ${CANONICAL_SUPABASE_PROJECT_ID}.`,
  );
}

const supabaseUrl = isCanonicalUrl(envUrl) ? envUrl : CANONICAL_SUPABASE_URL;

const supabasePublishableKey =
  envProjectId === CANONICAL_SUPABASE_PROJECT_ID && envKey ? envKey : CANONICAL_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
